name: thynui
description: something
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_i18n: ^0.19.1
  flutter_redux: ^0.6.0
  redux_epics: ^0.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/icons/spotify-black.png
    - assets/icons/spotify-white.png
